// 模拟兼职经历数据 - 7条数据（近半年内）
const practices = ref([
  {
    id: 1,
    companyName: '北京智学教育科技有限公司',
    position: '数学课程顾问',
    startDate: '2024-01-15',
    endDate: '2024-03-31',
    isCurrent: false,
    isCompleted: true,
    status: 'completed',
    statusText: '已结束',
    workDescription: '负责高中数学在线课程的研发和优化，参与课程体系设计，制定教学标准，指导教研团队进行课程内容开发。协助产品团队进行用户需求调研，优化课程体验，提升用户满意度。',
    monthlyHours: 40,
    totalHours: 100
  },
  {
    id: 2,
    companyName: '上海数学思维研究院',
    position: '高级研究员',
    startDate: '2024-02-01',
    endDate: null,
    isCurrent: true,
    isCompleted: false,
    status: 'current',
    statusText: '进行中',
    workDescription: '负责数学思维培养相关研究项目，包括理论框架构建、实践案例收集、教学效果评估等。参与制定行业标准，为教育机构提供专业咨询服务，推动数学教育创新发展。',
    monthlyHours: 30,
    totalHours: 90
  },
  {
    id: 3,
    companyName: '深圳创新教育集团',
    position: '教学总监',
    startDate: '2024-01-10',
    endDate: '2024-04-30',
    isCurrent: false,
    isCompleted: true,
    status: 'completed',
    statusText: '已结束',
    workDescription: '负责集团数学教学体系的整体规划和实施，建立教学质量监控体系，培训教师团队，提升整体教学水平。参与制定教学大纲和评价标准，推动教学改革和创新。',
    monthlyHours: 50,
    totalHours: 200
  },
  {
    id: 4,
    companyName: '广州智慧教育科技有限公司',
    position: '技术顾问',
    startDate: '2024-03-01',
    endDate: null,
    isCurrent: true,
    isCompleted: false,
    status: 'current',
    statusText: '进行中',
    workDescription: '为教育科技产品提供数学教学专业指导，参与AI教学系统的算法优化，设计个性化学习路径，提升系统智能化水平。协助产品团队进行功能设计和用户体验优化。',
    monthlyHours: 25,
    totalHours: 50
  },
  {
    id: 5,
    companyName: '杭州数学竞赛培训中心',
    position: '竞赛指导专家',
    startDate: '2024-02-15',
    endDate: '2024-05-31',
    isCurrent: false,
    isCompleted: true,
    status: 'completed',
    statusText: '已结束',
    workDescription: '负责高中数学竞赛培训课程的设计与实施，指导学生参加各类数学竞赛。开发竞赛培训教材，建立分层教学体系，培养学生在数学竞赛中的解题思维和应试技巧。',
    monthlyHours: 35,
    totalHours: 140
  },
  {
    id: 6,
    companyName: '成都教育科技研究院',
    position: '教研专家',
    startDate: '2024-04-01',
    endDate: null,
    isCurrent: true,
    isCompleted: false,
    status: 'current',
    statusText: '进行中',
    workDescription: '参与数学教育信息化项目研究，开发数字化教学资源，设计在线学习平台。负责教师培训课程开发，提升教师信息化教学能力，推动教育数字化转型。',
    monthlyHours: 20,
    totalHours: 40
  },
  {
    id: 7,
    companyName: '南京师范大学出版社',
    position: '教材编写顾问',
    startDate: '2024-01-20',
    endDate: '2024-06-15',
    isCurrent: false,
    isCompleted: true,
    status: 'completed',
    statusText: '已结束',
    workDescription: '参与高中数学教材的编写和修订工作，负责数学概念体系构建和习题设计。与编辑团队协作，确保教材内容的科学性、系统性和实用性，为全国高中数学教学提供优质资源。',
    monthlyHours: 45,
    totalHours: 225
  }
])
